# Generated by Django 5.0.6 on 2025-09-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_unique_together_and_more'),
        ('chat', '0002_initial'),
    ]

    operations = [
    ]
