# Generated by Django 5.0.6 on 2025-09-13 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price'), ('daily', 'Daily')], default='hourly', max_length=20)),
                ('estimated_duration', models.CharField(blank=True, help_text="e.g., '2 hours', '1 day', '3-5 days'", max_length=100)),
                ('requirements', models.TextField(blank=True, help_text='What the customer needs to provide')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
