# Generated by Django 5.0.6 on 2025-09-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('services', '0002_service'),
    ]

    operations = [
    ]
